### ISSUE TITLE
Game Integrity Checklist

### ISSUE THREAD

**Issue by fg123** [fg123/lumen-astrum-js#71]
For competitive integrity:

- [ ] Prevent server from crashing if one game crashes
- [ ] Verify source of state-changes from each client (client spoofing) against the socket
- [ ] Visibility System Overhaul
